/**
 * FlightResist AI 2.0 — Curated Enterprise Business Presets Catalog
 *
 * Provides 6 production-grade, globally distributed business travel presets:
 *  1. SIN-NRT: Singapore → Tokyo Narita via HKG (Singapore Airlines + Cathay Pacific)
 *  2. LHR-JFK: London Heathrow → New York JFK (British Airways Nonstop)
 *  3. SFO-HND: San Francisco → Tokyo Haneda (United Airlines Nonstop)
 *  4. SYD-LAX: Sydney → Los Angeles (Qantas Nonstop)
 *  5. DXB-CDG: Dubai → Paris CDG (Emirates Nonstop)
 *  6. FRA-SIN: Frankfurt → Singapore Changi (Lufthansa Nonstop)
 */

import type { PresetItinerary, PresetSummary, Itinerary } from './types';

export const DEFAULT_PRESET_ID = 'preset-sin-nrt';

export const PRESET_SIN_NRT: PresetItinerary = {
  id: 'preset-sin-nrt',
  tripId: 'TRIP-SIN-NRT-2026',
  presetName: 'Singapore → Tokyo Narita (via HKG)',
  tagline: 'Critical Infrastructure Signing · 1-Stop Transit',
  routeType: '1_STOP',
  tags: ['Enterprise', 'APAC', 'Typhoon Trami Risk', 'Multi-Leg'],
  origin: 'SIN',
  destination: 'NRT',
  travelDateIso: '2026-08-27T00:00:00+08:00',
  legs: [
    {
      flightNumber: 'SQ856',
      airlineCode: 'SQ',
      airlineName: 'Singapore Airlines',
      from: 'SIN',
      to: 'HKG',
      depIso: '2026-08-27T08:00:00+08:00',
      arrIso: '2026-08-27T12:05:00+08:00',
      durationMin: 245,
      aircraft: 'Airbus A350-900',
      cabin: 'Economy (Flexi)',
    },
    {
      flightNumber: 'CX520',
      airlineCode: 'CX',
      airlineName: 'Cathay Pacific',
      from: 'HKG',
      to: 'NRT',
      depIso: '2026-08-27T14:30:00+08:00',
      arrIso: '2026-08-27T19:45:00+09:00',
      durationMin: 255,
      aircraft: 'Boeing 777-300ER',
      cabin: 'Economy (Flexi)',
    },
  ],
  passenger: {
    name: 'Wei Chen',
    ticketReference: 'SQ-4471-XK2',
    loyaltyProgram: 'Singapore Airlines KrisFlyer',
    loyaltyTier: 'KrisFlyer Elite Gold',
    loyaltyNumber: 'SQ-KF-99281741',
    nationality: 'SG',
    passportNumber: 'E9823144A',
    passportExpiryIso: '2031-10-14',
    issuingCountry: 'SGP',
    contactEmail: 'wei.chen@novacapital.sg',
    contactPhone: '+65 9123 4567',
    checkedBags: 1,
    loyalty: 'KrisFlyer Elite Gold',
  },
  mission: {
    title: 'Contract signing — ¥2.1B infrastructure partnership',
    description: 'Infrastructure expansion partnership contract closing with Tokyo Metro Consortium. Board members departing same evening.',
    venue: 'Marunouchi client HQ, 28F Boardroom',
    location: 'Marunouchi, Tokyo',
    dealValue: 2100000000,
    dealCurrency: 'JPY',
    importance: 'CRITICAL',
    deadlineIso: '2026-08-28T08:30:00+09:00',
    timezone: 'Asia/Tokyo',
  },
  tripPurpose: 'Contract signing — ¥2.1B infrastructure partnership, Marunouchi client HQ',
  constraints: {
    budgetUsd: 150,
    mctMin: 60,
    arrivalDeadlineIso: '2026-08-27T23:59:00+09:00',
    hardArrivalLimitIso: '2026-08-28T12:00:00+09:00',
    baggagePieces: 1,
    baggageWeightKg: 23,
  },
  commitments: [
    {
      id: 'cm-transfer',
      kind: 'TRANSFER',
      label: 'Private airport transfer (prepaid)',
      detail: 'Chauffeur meet-and-greet, NRT Terminal 1 → Shinagawa',
      atIso: '2026-08-27T20:30:00+09:00',
      location: 'Narita Terminal 1',
    },
    {
      id: 'cm-hotel',
      kind: 'HOTEL',
      label: 'Shinagawa Prince Hotel — check-in',
      detail: 'Guaranteed late arrival, room held with card',
      atIso: '2026-08-27T22:00:00+09:00',
      location: 'Shinagawa, Tokyo',
    },
    {
      id: 'cm-meeting',
      kind: 'MEETING',
      label: 'Contract signing — Marunouchi client HQ',
      detail: 'The entire purpose of the trip. Client board flies out same day.',
      atIso: '2026-08-28T08:30:00+09:00',
      location: 'Marunouchi, Tokyo',
    },
  ],
};

export const PRESET_LHR_JFK: PresetItinerary = {
  id: 'preset-lhr-jfk',
  tripId: 'TRIP-LHR-JFK-2026',
  presetName: 'London Heathrow → New York JFK',
  tagline: 'Transatlantic M&A Closing · Direct Flagship',
  routeType: 'DIRECT',
  tags: ['Transatlantic', 'Direct', 'High-Yield M&A', 'Corporate'],
  origin: 'LHR',
  destination: 'JFK',
  travelDateIso: '2026-08-27T00:00:00+01:00',
  legs: [
    {
      flightNumber: 'BA117',
      airlineCode: 'BA',
      airlineName: 'British Airways',
      from: 'LHR',
      to: 'JFK',
      depIso: '2026-08-27T08:40:00+01:00',
      arrIso: '2026-08-27T11:30:00-04:00',
      durationMin: 470,
      aircraft: 'Boeing 777-200',
      cabin: 'Club World / Business',
    },
  ],
  passenger: {
    name: 'Victoria Sterling',
    ticketReference: 'BA-7792-NQ8',
    loyaltyProgram: 'British Airways Executive Club',
    loyaltyTier: 'Executive Club Gold',
    loyaltyNumber: 'BA-EC-40819233',
    nationality: 'GB',
    passportNumber: '552190823',
    passportExpiryIso: '2030-05-20',
    issuingCountry: 'GBR',
    contactEmail: 'v.sterling@apexpartners.co.uk',
    contactPhone: '+44 20 7946 0912',
    checkedBags: 2,
    loyalty: 'Executive Club Gold',
  },
  mission: {
    title: '$45M Cross-Atlantic PE Acquisition Closing',
    description: 'Final signing and funds release for transatlantic fintech buyout. Managing Partner and legal counsel in attendance.',
    venue: 'Hudson Yards 50, Level 44',
    location: 'New York, NY',
    dealValue: 45000000,
    dealCurrency: 'USD',
    importance: 'CRITICAL',
    deadlineIso: '2026-08-27T16:00:00-04:00',
    timezone: 'America/New_York',
  },
  tripPurpose: 'M&A Closing — $45M Cross-Atlantic Private Equity Acquisition, Hudson Yards NY',
  constraints: {
    budgetUsd: 350,
    mctMin: 75,
    arrivalDeadlineIso: '2026-08-27T14:00:00-04:00',
    hardArrivalLimitIso: '2026-08-28T09:00:00-04:00',
    baggagePieces: 2,
    baggageWeightKg: 23,
  },
  commitments: [
    {
      id: 'cm-transfer',
      kind: 'TRANSFER',
      label: 'Executive Car Transfer',
      detail: 'Pre-arranged sedan from JFK Terminal 7 to Manhattan',
      atIso: '2026-08-27T12:30:00-04:00',
      location: 'JFK Terminal 7',
    },
    {
      id: 'cm-hotel',
      kind: 'HOTEL',
      label: 'The Equinox Hotel Hudson Yards',
      detail: 'Check-in and executive suite preparation prior to closing session',
      atIso: '2026-08-27T14:00:00-04:00',
      location: 'Hudson Yards, New York',
    },
    {
      id: 'cm-meeting',
      kind: 'MEETING',
      label: 'PE Acquisition Closing & Escrow Release',
      detail: 'Definitive agreement execution with lead banking syndicate',
      atIso: '2026-08-27T16:30:00-04:00',
      location: '50 Hudson Yards, New York',
    },
  ],
};

export const PRESET_SFO_HND: PresetItinerary = {
  id: 'preset-sfo-hnd',
  tripId: 'TRIP-SFO-HND-2026',
  presetName: 'San Francisco → Tokyo Haneda',
  tagline: 'Transpacific VC Roadshow · Nonstop Polaris',
  routeType: 'DIRECT',
  tags: ['Transpacific', 'Tech VC', 'Polaris Direct', 'Executive'],
  origin: 'SFO',
  destination: 'HND',
  travelDateIso: '2026-08-27T00:00:00-07:00',
  legs: [
    {
      flightNumber: 'UA875',
      airlineCode: 'UA',
      airlineName: 'United Airlines',
      from: 'SFO',
      to: 'HND',
      depIso: '2026-08-27T10:45:00-07:00',
      arrIso: '2026-08-28T14:05:00+09:00',
      durationMin: 680,
      aircraft: 'Boeing 787-9 Dreamliner',
      cabin: 'United Polaris Business',
    },
  ],
  passenger: {
    name: 'Marcus Vance',
    ticketReference: 'UA-9031-KL5',
    loyaltyProgram: 'United MileagePlus',
    loyaltyTier: 'Premier 1K',
    loyaltyNumber: 'UA-MP-00847291',
    nationality: 'US',
    passportNumber: 'P481920311',
    passportExpiryIso: '2029-08-11',
    issuingCountry: 'USA',
    contactEmail: 'mvance@sequoiatech.io',
    contactPhone: '+1 415 890 2311',
    checkedBags: 2,
    loyalty: 'Premier 1K',
  },
  mission: {
    title: '$80M Series C Lead Term Sheet Finalization',
    description: 'Executive investor presentation and lead term sheet execution with sovereign tech investment fund.',
    venue: 'Roppongi Hills Mori Tower, 49F',
    location: 'Minato-ku, Tokyo',
    dealValue: 80000000,
    dealCurrency: 'USD',
    importance: 'CRITICAL',
    deadlineIso: '2026-08-28T18:00:00+09:00',
    timezone: 'Asia/Tokyo',
  },
  tripPurpose: 'Series C Term Sheet — $80M Sovereign Fund Lead, Roppongi Hills Tokyo',
  constraints: {
    budgetUsd: 400,
    mctMin: 60,
    arrivalDeadlineIso: '2026-08-28T16:00:00+09:00',
    hardArrivalLimitIso: '2026-08-29T10:00:00+09:00',
    baggagePieces: 2,
    baggageWeightKg: 32,
  },
  commitments: [
    {
      id: 'cm-transfer',
      kind: 'TRANSFER',
      label: 'Express Chauffeur HND → Roppongi',
      detail: 'Haneda International arrival lobby pickup',
      atIso: '2026-08-28T15:00:00+09:00',
      location: 'Haneda Terminal 3',
    },
    {
      id: 'cm-hotel',
      kind: 'HOTEL',
      label: 'Grand Hyatt Tokyo — Roppongi',
      detail: 'Executive room reservation with early access',
      atIso: '2026-08-28T16:00:00+09:00',
      location: 'Roppongi, Tokyo',
    },
    {
      id: 'cm-meeting',
      kind: 'MEETING',
      label: 'Series C Lead Investor Session',
      detail: 'Final syndicate sign-off on valuation and governance covenants',
      atIso: '2026-08-28T18:30:00+09:00',
      location: 'Roppongi Hills Mori Tower, Tokyo',
    },
  ],
};

export const PRESET_SYD_LAX: PresetItinerary = {
  id: 'preset-syd-lax',
  tripId: 'TRIP-SYD-LAX-2026',
  presetName: 'Sydney → Los Angeles',
  tagline: 'Transpacific Media Summit · A380 Flagship',
  routeType: 'DIRECT',
  tags: ['Oceania', 'Transpacific', 'Media / IP', 'Heavy Luggage'],
  origin: 'SYD',
  destination: 'LAX',
  travelDateIso: '2026-08-27T00:00:00+10:00',
  legs: [
    {
      flightNumber: 'QF11',
      airlineCode: 'QF',
      airlineName: 'Qantas',
      from: 'SYD',
      to: 'LAX',
      depIso: '2026-08-27T11:20:00+10:00',
      arrIso: '2026-08-27T07:15:00-07:00',
      durationMin: 835,
      aircraft: 'Airbus A380-800',
      cabin: 'International Business',
    },
  ],
  passenger: {
    name: 'Olivia Thornton',
    ticketReference: 'QF-5519-MR3',
    loyaltyProgram: 'Qantas Frequent Flyer',
    loyaltyTier: 'Platinum / OneWorld Emerald',
    loyaltyNumber: 'QF-FF-1849201',
    nationality: 'AU',
    passportNumber: 'N7201948',
    passportExpiryIso: '2032-03-09',
    issuingCountry: 'AUS',
    contactEmail: 'olivia.thornton@cinematicventures.com.au',
    contactPhone: '+61 2 8011 4455',
    checkedBags: 2,
    loyalty: 'Platinum',
  },
  mission: {
    title: '$120M Global Content Streaming Rights Summit',
    description: 'Exclusive studio licensing rights negotiation for multi-year APAC and global theatrical IP catalog.',
    venue: 'Century City Entertainment Center, Suite 1200',
    location: 'Century City, Los Angeles, CA',
    dealValue: 120000000,
    dealCurrency: 'USD',
    importance: 'CRITICAL',
    deadlineIso: '2026-08-27T14:00:00-07:00',
    timezone: 'America/Los_Angeles',
  },
  tripPurpose: 'IP Rights Licensing — $120M Studio Catalog Negotiation, Century City LA',
  constraints: {
    budgetUsd: 500,
    mctMin: 90,
    arrivalDeadlineIso: '2026-08-27T10:00:00-07:00',
    hardArrivalLimitIso: '2026-08-28T09:00:00-07:00',
    baggagePieces: 2,
    baggageWeightKg: 32,
  },
  commitments: [
    {
      id: 'cm-transfer',
      kind: 'TRANSFER',
      label: 'VIP Airside Escort & Private Transfer',
      detail: 'Tom Bradley International Terminal pickup to Century City',
      atIso: '2026-08-27T08:30:00-07:00',
      location: 'LAX TBIT',
    },
    {
      id: 'cm-hotel',
      kind: 'HOTEL',
      label: 'Fairmont Century Plaza',
      detail: 'Day-use suite for preparation and board briefing',
      atIso: '2026-08-27T10:00:00-07:00',
      location: 'Century City, Los Angeles',
    },
    {
      id: 'cm-meeting',
      kind: 'MEETING',
      label: 'Global Studio Licensing Syndicate',
      detail: 'Principal agreement signing for international streaming rights',
      atIso: '2026-08-27T14:30:00-07:00',
      location: 'Century City, Los Angeles',
    },
  ],
};

export const PRESET_DXB_CDG: PresetItinerary = {
  id: 'preset-dxb-cdg',
  tripId: 'TRIP-DXB-CDG-2026',
  presetName: 'Dubai → Paris Charles de Gaulle',
  tagline: 'Gulf-Europe Luxury JV · A380 First Service',
  routeType: 'DIRECT',
  tags: ['Middle East', 'Europe', 'Luxury / Retail', 'First Class'],
  origin: 'DXB',
  destination: 'CDG',
  travelDateIso: '2026-08-27T00:00:00+04:00',
  legs: [
    {
      flightNumber: 'EK73',
      airlineCode: 'EK',
      airlineName: 'Emirates',
      from: 'DXB',
      to: 'CDG',
      depIso: '2026-08-27T08:20:00+04:00',
      arrIso: '2026-08-27T13:30:00+02:00',
      durationMin: 430,
      aircraft: 'Airbus A380-800',
      cabin: 'First Class / Business',
    },
  ],
  passenger: {
    name: 'Tariq Al-Mansoor',
    ticketReference: 'EK-8821-XP7',
    loyaltyProgram: 'Emirates Skywards',
    loyaltyTier: 'Skywards Platinum',
    loyaltyNumber: 'EK-SK-5509124',
    nationality: 'AE',
    passportNumber: 'B9041824',
    passportExpiryIso: '2028-11-30',
    issuingCountry: 'ARE',
    contactEmail: 't.almansoor@gulfholding.ae',
    contactPhone: '+971 4 312 8899',
    checkedBags: 2,
    loyalty: 'Skywards Platinum',
  },
  mission: {
    title: '€32M Luxury Retail & Hospitality Joint Venture',
    description: 'Signing ceremony and press conference for flagship Middle East / European luxury hospitality partnership.',
    venue: 'Place Vendôme, Private Salon 4',
    location: '1er Arrondissement, Paris',
    dealValue: 32000000,
    dealCurrency: 'EUR',
    importance: 'CRITICAL',
    deadlineIso: '2026-08-27T18:00:00+02:00',
    timezone: 'Europe/Paris',
  },
  tripPurpose: 'Luxury Retail JV — €32M Place Vendôme Signing & Press Conference',
  constraints: {
    budgetUsd: 300,
    mctMin: 60,
    arrivalDeadlineIso: '2026-08-27T15:30:00+02:00',
    hardArrivalLimitIso: '2026-08-28T10:00:00+02:00',
    baggagePieces: 2,
    baggageWeightKg: 32,
  },
  commitments: [
    {
      id: 'cm-transfer',
      kind: 'TRANSFER',
      label: 'Prestige Chauffeur CDG → Vendôme',
      detail: 'CDG Terminal 2E airside meet and transfer to Central Paris',
      atIso: '2026-08-27T14:30:00+02:00',
      location: 'Paris Charles de Gaulle T2E',
    },
    {
      id: 'cm-hotel',
      kind: 'HOTEL',
      label: 'Ritz Paris — Place Vendôme',
      detail: 'Prestige suite reservation with security protocol',
      atIso: '2026-08-27T15:45:00+02:00',
      location: 'Place Vendôme, Paris',
    },
    {
      id: 'cm-meeting',
      kind: 'MEETING',
      label: 'Luxury Brand JV Protocol & Signing',
      detail: 'Bilateral joint venture signing and official press announcement',
      atIso: '2026-08-27T18:30:00+02:00',
      location: 'Place Vendôme, Paris',
    },
  ],
};

export const PRESET_FRA_SIN: PresetItinerary = {
  id: 'preset-fra-sin',
  tripId: 'TRIP-FRA-SIN-2026',
  presetName: 'Frankfurt → Singapore Changi',
  tagline: 'Europe-Asia Semi Summit · Nonstop A350',
  routeType: 'DIRECT',
  tags: ['Europe', 'APAC', 'Semiconductors', 'Direct'],
  origin: 'FRA',
  destination: 'SIN',
  travelDateIso: '2026-08-27T00:00:00+02:00',
  legs: [
    {
      flightNumber: 'LH778',
      airlineCode: 'LH',
      airlineName: 'Lufthansa',
      from: 'FRA',
      to: 'SIN',
      depIso: '2026-08-27T21:55:00+02:00',
      arrIso: '2026-08-28T16:15:00+08:00',
      durationMin: 740,
      aircraft: 'Airbus A350-900',
      cabin: 'Business Class',
    },
  ],
  passenger: {
    name: 'Dr. Henrik Schmidt',
    ticketReference: 'LH-4910-BW9',
    loyaltyProgram: 'Lufthansa Miles & More',
    loyaltyTier: 'Senator / Star Alliance Gold',
    loyaltyNumber: 'LH-MM-7729103',
    nationality: 'DE',
    passportNumber: 'C81920392',
    passportExpiryIso: '2030-01-15',
    issuingCountry: 'DEU',
    contactEmail: 'henrik.schmidt@fraunhofer-semi.de',
    contactPhone: '+49 69 798 2210',
    checkedBags: 2,
    loyalty: 'Senator',
  },
  mission: {
    title: '$65M Semiconductor Supply Chain Consortium Keynote',
    description: 'Opening keynote and consortium governance charter signing with GlobalFoundries and Singapore EDB.',
    venue: 'Marina Bay Financial Centre Tower 2, Level 38',
    location: 'Marina Bay, Singapore',
    dealValue: 65000000,
    dealCurrency: 'USD',
    importance: 'CRITICAL',
    deadlineIso: '2026-08-28T19:30:00+08:00',
    timezone: 'Asia/Singapore',
  },
  tripPurpose: 'Semi Consortium Keynote — $65M MBFC Singapore Summit',
  constraints: {
    budgetUsd: 450,
    mctMin: 60,
    arrivalDeadlineIso: '2026-08-28T17:30:00+08:00',
    hardArrivalLimitIso: '2026-08-29T09:00:00+08:00',
    baggagePieces: 2,
    baggageWeightKg: 23,
  },
  commitments: [
    {
      id: 'cm-transfer',
      kind: 'TRANSFER',
      label: 'Changi Chauffeur SIN → Marina Bay',
      detail: 'Changi Terminal 2 Jewel pickup and express transfer to MBFC',
      atIso: '2026-08-28T17:00:00+08:00',
      location: 'Singapore Changi Terminal 2',
    },
    {
      id: 'cm-hotel',
      kind: 'HOTEL',
      label: 'Marina Bay Sands — Premier Suite',
      detail: 'Guaranteed express check-in and wardrobe service',
      atIso: '2026-08-28T18:00:00+08:00',
      location: 'Marina Bay, Singapore',
    },
    {
      id: 'cm-meeting',
      kind: 'MEETING',
      label: 'Consortium Charter Keynote & Dinner',
      detail: 'Keynote address and sovereign fab capacity allocation signing',
      atIso: '2026-08-28T19:45:00+08:00',
      location: 'MBFC Tower 2, Singapore',
    },
  ],
};

export const PRESETS: PresetItinerary[] = [
  PRESET_SIN_NRT,
  PRESET_LHR_JFK,
  PRESET_SFO_HND,
  PRESET_SYD_LAX,
  PRESET_DXB_CDG,
  PRESET_FRA_SIN,
];

export function getAllPresets(): PresetItinerary[] {
  return PRESETS;
}

export function getPresetById(id: string | undefined): PresetItinerary | undefined {
  if (!id) return undefined;
  return PRESETS.find((p) => p.id.toLowerCase() === id.toLowerCase() || p.tripId.toLowerCase() === id.toLowerCase());
}

export function getPresetSummaries(): PresetSummary[] {
  return PRESETS.map((p) => ({
    id: p.id,
    tripId: p.tripId,
    name: p.presetName,
    origin: p.origin,
    destination: p.destination,
    travelDateIso: p.travelDateIso,
    tagline: p.tagline,
    routeType: p.routeType,
    tags: p.tags,
    legsCount: p.legs.length,
    primaryAirline: p.legs[0]?.airlineName ?? 'Unknown Airline',
    dealValue: p.mission?.dealValue,
    dealCurrency: p.mission?.dealCurrency,
    budgetUsd: p.constraints.budgetUsd,
  }));
}

/** Helper to deep clone an itinerary */
export function cloneItinerary(itinerary: Itinerary): Itinerary {
  return JSON.parse(JSON.stringify(itinerary)) as Itinerary;
}
